directory_json_location: '..\_10_24_2016_json_directory_building\data_json'
json_file_name: 'sample_output1478461924.298723.json' 

modify_previous_feature: True
pkl_file_location: None

features:
  hsv_color_histogram: True
  gray_color_histogram: True
